namespace Fbx2Vmd.FBXImporter
{
    internal static class YybVisualComparisonRunProfile
    {
        internal const string DefaultFbxFileName = "satisfaction_2.fbx";
        internal const float DefaultDurationSeconds = 31f;
        internal const float DefaultManualAnimatorBodyRotationReferenceWeight = 1f;
        internal const float DefaultManualAnimatorFullBodyPoseReferenceWeight = 1f;
        internal const float DefaultManualAnimatorFullBodyPoseReferenceFrameGateStart = 0f;
        internal const float DefaultManualAnimatorFullBodyPoseReferenceFrameGateEnd = 0f;
        internal const float DefaultSetHumanPoseRightLegTwistOutputReferenceWeight = 1f;
        internal const float DefaultSetHumanPoseRightLegTwistOutputReferenceMaxDelta = 0.02f;
        internal const float DefaultManualAnimatorHandPalmFrameWeight = 1f;
        internal const float DefaultRetargetPoseVisualSpikeCurrentWeight = 0.65f;
        internal const float DefaultRetargetPoseVisualSpikeForearmStretchClampMaxOffset = 0f;
        internal const float DefaultRetargetArmStretchMuscleLimit = 0.5f;
        internal const float DefaultManualAnimatorHipsLocalPositionReferenceWeight = 0.25f;
        internal const float DefaultManualAnimatorHipsLocalPositionReferenceMaxOffset = 0.04f;
        internal const float DefaultManualAnimatorBodyPositionXzReferenceWeight = 0.45f;
        internal const float DefaultManualAnimatorBodyPositionXzReferenceMaxOffset = 0.025f;
        internal const float DefaultManualAnimatorBodyPositionXzReferenceFrameGateStart = 0f;
        internal const float DefaultManualAnimatorBodyPositionXzReferenceFrameGateEnd = 0f;
        internal const float DefaultManualAnimatorBodyPositionXzReferenceFrameGateBlendFrames = 0f;
        internal const float DefaultManualAnimatorBodyPositionXzReferenceAxisXScale = 1f;
        internal const float DefaultManualAnimatorBodyPositionXzReferenceAxisZScale = 1f;
        internal const float DefaultYybRightSleeveSilhouetteLocalOffsetX = 0f;
        internal const float DefaultYybRightSleeveSilhouetteLocalOffsetFrameGateStart = 0f;
        internal const float DefaultYybRightSleeveSilhouetteLocalOffsetFrameGateEnd = 0f;
        internal const float DefaultManualAnimatorBipedIkFootPositionReferenceWeight = 0.65f;
        internal const float DefaultManualAnimatorBipedIkFootPositionReferenceMaxOffset = 0.12f;
        internal const float DefaultPostSetHumanPoseRightEndpointPositionReferenceWeight = 1f;
        internal const float DefaultPostSetHumanPoseRightEndpointPositionReferenceMaxOffset = 0.04f;
        internal const float DefaultPostSetHumanPoseRightEndpointPositionReferencePositiveZScale = 1f;
        internal const float DefaultPostSetHumanPoseRightEndpointPositionReferenceToesBlendWeight = 1f;
        internal const float DefaultPostSetHumanPoseRightEndpointPositionReferenceFrameGateStart = 0f;
        internal const float DefaultPostSetHumanPoseRightEndpointPositionReferenceFrameGateEnd = 0f;
        internal const float DefaultPostSetHumanPoseRightFootEvaluatorXzReferenceTargetMagnitude = 0.049f;
        internal const float DefaultPreSetHumanPoseRightEndpointPositionReferenceWeight = 1f;
        internal const float DefaultPreSetHumanPoseRightEndpointPositionReferenceMaxOffset = 0.025f;
        internal const float DefaultPreSetHumanPoseRightEndpointPositionReferencePositiveZScale = 1f;
        internal const float DefaultPreSetHumanPoseRightEndpointPositionReferenceToesBlendWeight = 1f;
        internal const float DefaultPreSetHumanPoseRightEndpointPositionReferenceFrameGateStart = 0f;
        internal const float DefaultPreSetHumanPoseRightEndpointPositionReferenceFrameGateEnd = 0f;
        internal const float DefaultManualAnimatorFootHipsAlignedResidualYawReferenceWeight = 1f;
        internal const float DefaultManualAnimatorFootHipsAlignedResidualYawReferenceMaxAngle = 15f;
        internal const float DefaultManualAnimatorLowerBodySegmentDirectionReferenceWeight = 1f;
        internal const float DefaultManualAnimatorLowerBodySegmentDirectionReferenceMaxAngle = 6.2f;
        internal const float DefaultManualAnimatorUpperLegToLowerLegSegmentDirectionReferenceMaxAngle = 0f;
        internal const float DefaultManualAnimatorLowerLegToFootSegmentDirectionReferenceMaxAngle = 0f;
        internal const float DefaultManualAnimatorLeftLowerLegToFootSegmentDirectionReferenceMaxAngle = 0f;
        internal const float DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceMaxAngle = 0f;
        internal const float DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceAxisXzScale = 1f;
        internal const float DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceBlendWeight = 0.125f;
        internal const float DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceFrameGateStart = 0f;
        internal const float DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceFrameGateEnd = 0f;
        internal const float DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceEndpointBlendWeight = 1f;
        internal const float DefaultManualAnimatorFootToToesSegmentDirectionReferenceMaxAngle = 0f;
        internal const float DefaultYybArmSwingLimitWeight = 0.85f;
        internal const float DefaultYybArmSwingMaxDownDot = 0.68f;
        internal const float DefaultYybArmSwingMinHandHorizontalRatio = 0.05f;
        internal const float DefaultYybArmSwingMaxHandBelowShoulderRatio = 0.75f;
        internal const float DefaultYybArmSwingHorizontalReachLimitWeight = 0f;
        internal const float DefaultYybArmSwingMaxHandHorizontalReachRatio = 0f;
        internal const float DefaultYybArmSwingHorizontalReachMaxHandBelowShoulderRatio = 0f;
        internal const float DefaultYybArmSwingHorizontalReachMinElbowAngleAfterApply = 0f;
        internal const float DefaultYybArmSwingRaisedPoseHorizontalReachLimitWeight = 0.2f;
        internal const float DefaultYybArmSwingRaisedPoseMinUpperArmDownDot = 0.55f;
        internal const float DefaultYybArmSwingRaisedPoseMaxHandBelowShoulderRatio = 0.05f;
        internal const float DefaultYybArmSwingRaisedPoseMaxHandHorizontalReachRatio = 0.55f;
        internal const float DefaultYybArmDirectionUpperArmWeight = 0.65f;
        internal const float DefaultYybArmDirectionForearmWeight = 0.75f;
        internal const float DefaultYybArmDirectionUpperArmMaxDegrees = 65f;
        internal const float DefaultYybArmDirectionForearmMaxDegrees = 85f;
        internal const float DefaultYybArmDirectionLeftSideWeightScale = 1f;
        internal const float DefaultYybArmDirectionRightSideWeightScale = 1f;
        internal const float DefaultYybArmSleeveAnchorInfluence = 0.825f;
        internal const float DefaultYybArmShoulderCapAnchorInfluence = 0f;
        internal const float DefaultYybArmSleeveAnchorMaxDegrees = 85f;
        internal const float DefaultYybArmVisualUpperArmInfluence = 0.35f;
        internal const float DefaultYybArmVisualForearmInfluence = 0.75f;
        internal const float DefaultYybArmVisualUpperArmMaxDegrees = 45f;
        internal const float DefaultYybArmVisualForearmMaxDegrees = 75f;
        internal const float NoMmdIkDeltaGuardLimitOverrideVmd = float.NaN;
        internal const int NoMmdIkDeltaGuardRecoveryHoldFrames = -1;
        internal const int NoDiagnosticCaptureDimensionOverride = 0;
        internal const float NoDiagnosticScreenshotFramingOverride = float.NaN;

        internal static YybVisualComparisonRunOptions CreateDefaultOptions()
        {
            return new YybVisualComparisonRunOptions
            {
                fbxFileName = DefaultFbxFileName,
                durationSeconds = DefaultDurationSeconds,
                enableFingerCloseups = false,
                enableRecorderParentFrameIkOffsetsWhenCenterParented = true,
                mmdIkDeltaGuardLimitOverrideVmd = NoMmdIkDeltaGuardLimitOverrideVmd,
                mmdIkDeltaGuardRecoveryTriggerVmd = NoMmdIkDeltaGuardLimitOverrideVmd,
                mmdIkDeltaGuardRecoveryDebtThresholdVmd = NoMmdIkDeltaGuardLimitOverrideVmd,
                mmdIkDeltaGuardRecoveryHoldFrames = NoMmdIkDeltaGuardRecoveryHoldFrames,
                enableFinalIkFootGroundingRuntimeOverride = false,
                enableManualAnimatorFootLocalRotationRuntimeOverride = false,
                disableManualAnimatorFootLocalRotationRuntimeOverride = false,
                enableManualAnimatorFullBodyPoseRuntimeOverride = false,
                disableManualAnimatorFullBodyPoseRuntimeOverride = false,
                manualAnimatorFullBodyPoseReferenceWeight = DefaultManualAnimatorFullBodyPoseReferenceWeight,
                manualAnimatorFullBodyPoseExcludeLowerBodyMusclesRuntimeOverride = false,
                manualAnimatorFullBodyPoseLowerBodyMusclesOnlyRuntimeOverride = false,
                manualAnimatorFullBodyPoseLegTwistMusclesOnlyRuntimeOverride = false,
                manualAnimatorFullBodyPoseRightArmMusclesOnlyRuntimeOverride = false,
                manualAnimatorFullBodyPoseLeftArmMusclesOnlyRuntimeOverride = false,
                manualAnimatorFullBodyPoseRightSleeveChainMusclesOnlyRuntimeOverride = false,
                manualAnimatorFullBodyPoseReferenceFrameGateStart = DefaultManualAnimatorFullBodyPoseReferenceFrameGateStart,
                manualAnimatorFullBodyPoseReferenceFrameGateEnd = DefaultManualAnimatorFullBodyPoseReferenceFrameGateEnd,
                enableSetHumanPoseRightLegTwistOutputReferenceRuntimeOverride = false,
                setHumanPoseRightLegTwistOutputReferenceWeight = DefaultSetHumanPoseRightLegTwistOutputReferenceWeight,
                setHumanPoseRightLegTwistOutputReferenceMaxDelta = DefaultSetHumanPoseRightLegTwistOutputReferenceMaxDelta,
                enableManualAnimatorBodyRotationRuntimeOverride = false,
                disableManualAnimatorBodyRotationRuntimeOverride = false,
                manualAnimatorBodyRotationReferenceWeight = DefaultManualAnimatorBodyRotationReferenceWeight,
                enableManualAnimatorHandLocalRotationRuntimeOverride = false,
                enableManualAnimatorThumbLocalRotationRuntimeOverride = false,
                enableManualAnimatorHandPalmFrameRuntimeOverride = false,
                manualAnimatorHandPalmFrameWeight = DefaultManualAnimatorHandPalmFrameWeight,
                overrideRetargetPoseVisualSpikeSmoothingRuntimeSettings = false,
                enableRetargetPoseVisualSpikeSmoothingRuntimeOverride = true,
                retargetPoseVisualSpikeCurrentWeight = DefaultRetargetPoseVisualSpikeCurrentWeight,
                retargetPoseVisualSpikeForearmStretchClampMaxOffset = DefaultRetargetPoseVisualSpikeForearmStretchClampMaxOffset,
                enableRetargetArmStretchClampRuntimeOverride = false,
                retargetArmStretchMuscleLimit = DefaultRetargetArmStretchMuscleLimit,
                enableYybArmSwingLimitRuntimeOverride = false,
                yybArmSwingLimitWeight = DefaultYybArmSwingLimitWeight,
                yybArmSwingMaxDownDot = DefaultYybArmSwingMaxDownDot,
                yybArmSwingMinHandHorizontalRatio = DefaultYybArmSwingMinHandHorizontalRatio,
                yybArmSwingMaxHandBelowShoulderRatio = DefaultYybArmSwingMaxHandBelowShoulderRatio,
                yybArmSwingHorizontalReachLimitWeight = DefaultYybArmSwingHorizontalReachLimitWeight,
                yybArmSwingMaxHandHorizontalReachRatio = DefaultYybArmSwingMaxHandHorizontalReachRatio,
                yybArmSwingHorizontalReachMaxHandBelowShoulderRatio = DefaultYybArmSwingHorizontalReachMaxHandBelowShoulderRatio,
                yybArmSwingHorizontalReachMinElbowAngleAfterApply = DefaultYybArmSwingHorizontalReachMinElbowAngleAfterApply,
                yybArmSwingRaisedPoseHorizontalReachLimitWeight = DefaultYybArmSwingRaisedPoseHorizontalReachLimitWeight,
                yybArmSwingRaisedPoseMinUpperArmDownDot = DefaultYybArmSwingRaisedPoseMinUpperArmDownDot,
                yybArmSwingRaisedPoseMaxHandBelowShoulderRatio = DefaultYybArmSwingRaisedPoseMaxHandBelowShoulderRatio,
                yybArmSwingRaisedPoseMaxHandHorizontalReachRatio = DefaultYybArmSwingRaisedPoseMaxHandHorizontalReachRatio,
                enableYybArmDirectionRetargetRuntimeOverride = false,
                yybArmDirectionUpperArmWeight = DefaultYybArmDirectionUpperArmWeight,
                yybArmDirectionForearmWeight = DefaultYybArmDirectionForearmWeight,
                yybArmDirectionUpperArmMaxDegrees = DefaultYybArmDirectionUpperArmMaxDegrees,
                yybArmDirectionForearmMaxDegrees = DefaultYybArmDirectionForearmMaxDegrees,
                yybArmDirectionLeftSideWeightScale = DefaultYybArmDirectionLeftSideWeightScale,
                yybArmDirectionRightSideWeightScale = DefaultYybArmDirectionRightSideWeightScale,
                overrideYybArmSleeveAnchorRuntimeSettings = false,
                enableYybArmSleeveAnchorRuntimeOverride = true,
                yybArmSleeveAnchorInfluence = DefaultYybArmSleeveAnchorInfluence,
                yybArmShoulderCapAnchorInfluence = DefaultYybArmShoulderCapAnchorInfluence,
                yybArmSleeveAnchorMaxDegrees = DefaultYybArmSleeveAnchorMaxDegrees,
                overrideYybArmVisualTwistRuntimeSettings = false,
                enableYybArmVisualTwistRuntimeOverride = true,
                yybArmVisualUpperArmInfluence = DefaultYybArmVisualUpperArmInfluence,
                yybArmVisualForearmInfluence = DefaultYybArmVisualForearmInfluence,
                yybArmVisualUpperArmMaxDegrees = DefaultYybArmVisualUpperArmMaxDegrees,
                yybArmVisualForearmMaxDegrees = DefaultYybArmVisualForearmMaxDegrees,
                enableManualAnimatorLowerBodySegmentDirectionRuntimeOverride = false,
                disableManualAnimatorLowerBodySegmentDirectionRuntimeOverride = false,
                manualAnimatorLowerBodySegmentDirectionReferenceWeight = DefaultManualAnimatorLowerBodySegmentDirectionReferenceWeight,
                manualAnimatorLowerBodySegmentDirectionReferenceMaxAngle = DefaultManualAnimatorLowerBodySegmentDirectionReferenceMaxAngle,
                disableManualAnimatorUpperLegToLowerLegSegmentDirectionRuntimeOverride = false,
                manualAnimatorUpperLegToLowerLegSegmentDirectionReferenceMaxAngle = DefaultManualAnimatorUpperLegToLowerLegSegmentDirectionReferenceMaxAngle,
                disableManualAnimatorLowerLegToFootSegmentDirectionRuntimeOverride = false,
                manualAnimatorLowerLegToFootSegmentDirectionReferenceMaxAngle = DefaultManualAnimatorLowerLegToFootSegmentDirectionReferenceMaxAngle,
                manualAnimatorLeftLowerLegToFootSegmentDirectionReferenceMaxAngle = DefaultManualAnimatorLeftLowerLegToFootSegmentDirectionReferenceMaxAngle,
                manualAnimatorRightLowerLegToFootSegmentDirectionReferenceMaxAngle = DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceMaxAngle,
                manualAnimatorRightLowerLegToFootSegmentDirectionReferenceAxisXzScale = DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceAxisXzScale,
                manualAnimatorRightLowerLegToFootSegmentDirectionReferenceBlendWeight = DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceBlendWeight,
                manualAnimatorRightLowerLegToFootSegmentDirectionReferenceFrameGateStart = DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceFrameGateStart,
                manualAnimatorRightLowerLegToFootSegmentDirectionReferenceFrameGateEnd = DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceFrameGateEnd,
                manualAnimatorRightLowerLegToFootSegmentDirectionReferenceEndpointBlendWeight = DefaultManualAnimatorRightLowerLegToFootSegmentDirectionReferenceEndpointBlendWeight,
                disableManualAnimatorFootToToesSegmentDirectionRuntimeOverride = false,
                manualAnimatorFootToToesSegmentDirectionReferenceMaxAngle = DefaultManualAnimatorFootToToesSegmentDirectionReferenceMaxAngle,
                enableManualAnimatorFootHipsAlignedResidualYawRuntimeOverride = false,
                disableManualAnimatorFootHipsAlignedResidualYawRuntimeOverride = false,
                manualAnimatorFootHipsAlignedResidualYawReferenceWeight = DefaultManualAnimatorFootHipsAlignedResidualYawReferenceWeight,
                manualAnimatorFootHipsAlignedResidualYawReferenceMaxAngle = DefaultManualAnimatorFootHipsAlignedResidualYawReferenceMaxAngle,
                enablePostSetHumanPoseRightEndpointPositionRuntimeOverride = false,
                postSetHumanPoseRightEndpointPositionReferenceWeight = DefaultPostSetHumanPoseRightEndpointPositionReferenceWeight,
                postSetHumanPoseRightEndpointPositionReferenceMaxOffset = DefaultPostSetHumanPoseRightEndpointPositionReferenceMaxOffset,
                postSetHumanPoseRightEndpointPositionReferencePositiveZScale = DefaultPostSetHumanPoseRightEndpointPositionReferencePositiveZScale,
                postSetHumanPoseRightEndpointPositionReferenceToesBlendWeight = DefaultPostSetHumanPoseRightEndpointPositionReferenceToesBlendWeight,
                postSetHumanPoseRightEndpointPositionReferenceFrameGateStart = DefaultPostSetHumanPoseRightEndpointPositionReferenceFrameGateStart,
                postSetHumanPoseRightEndpointPositionReferenceFrameGateEnd = DefaultPostSetHumanPoseRightEndpointPositionReferenceFrameGateEnd,
                ShouldUseLeftSideForPostSetHumanPoseEndpointPosition = false,
                enablePreSetHumanPoseRightEndpointPositionRuntimeOverride = false,
                preSetHumanPoseRightEndpointPositionReferenceWeight = DefaultPreSetHumanPoseRightEndpointPositionReferenceWeight,
                preSetHumanPoseRightEndpointPositionReferenceMaxOffset = DefaultPreSetHumanPoseRightEndpointPositionReferenceMaxOffset,
                preSetHumanPoseRightEndpointPositionReferencePositiveZScale = DefaultPreSetHumanPoseRightEndpointPositionReferencePositiveZScale,
                preSetHumanPoseRightEndpointPositionReferenceToesBlendWeight = DefaultPreSetHumanPoseRightEndpointPositionReferenceToesBlendWeight,
                preSetHumanPoseRightEndpointPositionReferenceFrameGateStart = DefaultPreSetHumanPoseRightEndpointPositionReferenceFrameGateStart,
                preSetHumanPoseRightEndpointPositionReferenceFrameGateEnd = DefaultPreSetHumanPoseRightEndpointPositionReferenceFrameGateEnd,
                ShouldUseLeftSideForPreSetHumanPoseEndpointPosition = false,
                preSetHumanPoseEndpointPositionUseGhostCurrentBasis = false,
                ShouldInvertPreSetHumanPoseEndpointPositionBodyX = false,
                ShouldInvertPreSetHumanPoseEndpointPositionBodyZ = false,
                usePostSetHumanPoseRightFootEvaluatorXzReference = false,
                postSetHumanPoseRightFootEvaluatorXzReferenceTargetMagnitude = DefaultPostSetHumanPoseRightFootEvaluatorXzReferenceTargetMagnitude,
                enableManualAnimatorBipedIkFootPositionRuntimeOverride = false,
                manualAnimatorBipedIkFootPositionReferenceWeight = DefaultManualAnimatorBipedIkFootPositionReferenceWeight,
                manualAnimatorBipedIkFootPositionReferenceMaxOffset = DefaultManualAnimatorBipedIkFootPositionReferenceMaxOffset,
                enableManualAnimatorHipsLocalPositionRuntimeOverride = false,
                manualAnimatorHipsLocalPositionReferenceWeight = DefaultManualAnimatorHipsLocalPositionReferenceWeight,
                manualAnimatorHipsLocalPositionReferenceMaxOffset = DefaultManualAnimatorHipsLocalPositionReferenceMaxOffset,
                enableManualAnimatorBodyPositionXzRuntimeOverride = false,
                manualAnimatorBodyPositionXzReferenceWeight = DefaultManualAnimatorBodyPositionXzReferenceWeight,
                manualAnimatorBodyPositionXzReferenceMaxOffset = DefaultManualAnimatorBodyPositionXzReferenceMaxOffset,
                manualAnimatorBodyPositionXzReferenceFrameGateStart = DefaultManualAnimatorBodyPositionXzReferenceFrameGateStart,
                manualAnimatorBodyPositionXzReferenceFrameGateEnd = DefaultManualAnimatorBodyPositionXzReferenceFrameGateEnd,
                manualAnimatorBodyPositionXzReferenceFrameGateBlendFrames = DefaultManualAnimatorBodyPositionXzReferenceFrameGateBlendFrames,
                manualAnimatorBodyPositionXzReferenceAxisXScale = DefaultManualAnimatorBodyPositionXzReferenceAxisXScale,
                manualAnimatorBodyPositionXzReferenceAxisZScale = DefaultManualAnimatorBodyPositionXzReferenceAxisZScale,
                enableYybRightSleeveSilhouetteOffsetRuntimeOverride = false,
                yybRightSleeveSilhouetteLocalOffsetX = DefaultYybRightSleeveSilhouetteLocalOffsetX,
                yybRightSleeveSilhouetteLocalOffsetFrameGateStart = DefaultYybRightSleeveSilhouetteLocalOffsetFrameGateStart,
                yybRightSleeveSilhouetteLocalOffsetFrameGateEnd = DefaultYybRightSleeveSilhouetteLocalOffsetFrameGateEnd,
                disableTargetHumanoidBonePositionLockRuntimeOverride = false,
                enableRetargetBodyPositionXzRootMotionRuntimeOverride = false,
                enableVmdPlaybackProbeRuntimeOverride = false,
                applyVmdPlaybackProbeIkTargetsRuntimeOverride = false,
                editorDiagnosticSmokeSegment = "head",
                enableReferenceMmdTimingRuntimeOverride = false,
                diagnosticCaptureWidthOverride = NoDiagnosticCaptureDimensionOverride,
                diagnosticCaptureHeightOverride = NoDiagnosticCaptureDimensionOverride,
                diagnosticScreenshotPaddingOverride = NoDiagnosticScreenshotFramingOverride,
                diagnosticScreenshotVerticalViewportCenterOverride = NoDiagnosticScreenshotFramingOverride
            };
        }
    }
}
